package com.blackdragon2447.codex.models;

import static com.blackdragon2447.codex.models.Skills.SkillType.*;

public enum Skills {

  ACADEMICS(SMARTS),
  ATHLETICS(AGILITY), //*
  BATTLE(SMARTS),
  BOATING(SMARTS),
  COMMON_KNOWLEDGE(SMARTS), //*
  DRIVING(AGILITY),
  ELECTRONICS(SMARTS),
  FAITH(SPIRITS),
  FIGHTING(AGILITY),
  FOCUS(SPIRITS),
  GAMBLING(SMARTS),
  HACKING(SMARTS),
  HEALING(SMARTS),
  INTIMIDATION(SPIRITS),
  LANGUAGE(SMARTS),
  NOTICE(SMARTS), //*
  OCCULT(SMARTS),
  PERFORMANCE(SPIRITS),
  PERSUASION(SPIRITS), //*
  PILOTING(AGILITY),
  PSIONICS(SMARTS),
  REPAIR(SMARTS),
  RESEARCH(SMARTS),
  RIDING(AGILITY),
  SCIENCE(SMARTS),
  SHOOTING(AGILITY),
  SPELLCASTING(SMARTS),
  STEALTH(AGILITY), //*
  SURVIVAL(SMARTS),
  TAUNT(SMARTS),
  THIEVERY(AGILITY),
  WIERD_SCIENCE(SMARTS);

  final SkillType linkedSkill;

  private Skills(SkillType linkedSkill) { this.linkedSkill = linkedSkill; }

  public enum SkillType {
    AGILITY,
    SMARTS,
    SPIRITS,
    STRENGHT,
    VIGOR;
  }
}
