/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.blackdragon2447.codex;

import java.util.logging.Level;

import com.blackdragon2447.codex.util.CodexLogger;

public class App {

    public static void main(String[] args) {
      CodexLogger.log("Starting Codex", Level.INFO);
    

    }
}
